/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список доступных папок с вложенными проектами */
        get: operations["listFolders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список уроков проекта */
        get: operations["listProjectLessons"];
        put?: never;
        /** Добавить урок в проект через загрузку аудиофайла */
        post: operations["createProjectLessonFromAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FoldersResponse: {
            data: components["schemas"]["FolderWithProjects"][];
        };
        FolderWithProjects: components["schemas"]["Folder"] & {
            projects: components["schemas"]["Project"][];
        };
        Folder: {
            /** @example 12 */
            id: number;
            /** @example Курсы */
            name: string;
            /** @example false */
            hidden: boolean;
            /** @example 2 */
            projects_count: number;
        };
        Project: {
            /** @example 101 */
            id: number;
            /** @example 12 */
            folder_id: number;
            /** @example История кино */
            name: string;
            /** @example 8 */
            lessons_count: number;
            /** @example 14400 */
            duration_seconds: number | null;
            /** @example 4ч 0м */
            duration_label: string | null;
            /** @example 7 */
            default_pipeline_version_id: number | null;
            /** @example https://example.com/course */
            referer: string | null;
            /**
             * Format: date-time
             * @example 2026-03-18T09:15:00+00:00
             */
            updated_at: string | null;
        };
        ProjectLessonsResponse: {
            data: {
                project: components["schemas"]["Project"];
                pipeline_versions: components["schemas"]["PipelineVersionOption"][];
                lessons: components["schemas"]["Lesson"][];
            };
        };
        ProjectLessonCreateResponse: {
            data: {
                project: components["schemas"]["Project"];
                lesson: components["schemas"]["Lesson"];
            };
        };
        PipelineVersionOption: {
            /** @example 7 */
            id: number;
            /** @example Базовый шаблон • v3 */
            label: string;
            /** @example Базовая обработка лекции */
            description: string | null;
        };
        Lesson: {
            /** @example 503 */
            id: number;
            /** @example 101 */
            project_id: number;
            /** @example Новая лекция */
            name: string;
            /** @example lessons/503.mp3 */
            source_filename: string | null;
            /** @example https://www.youtube.com/watch?v=abc123 */
            source_url: string | null;
            /** @example 1800 */
            audio_duration_seconds: number | null;
            /** @example 30м */
            audio_duration_label: string | null;
            /**
             * @example running
             * @enum {string}
             */
            download_status: "queued" | "running" | "failed" | "loaded";
            runs: components["schemas"]["PipelineRunSummary"][];
        };
        PipelineRunSummary: {
            /** @example 9003 */
            id: number;
            /** @example 503 */
            lesson_id: number;
            /**
             * @example queued
             * @enum {string}
             */
            status: "queued" | "running" | "paused" | "failed" | "done";
            /** @example 7 */
            pipeline_version_id: number | null;
            /** @example Базовый шаблон */
            pipeline_title: string | null;
            /** @example 3 */
            pipeline_version: number | null;
            /** @example Базовый шаблон • v3 */
            pipeline_label: string | null;
            /** @example 3 */
            steps_count: number;
            /** @example 0 */
            done_steps_count: number;
            /**
             * Format: date-time
             * @example 2026-03-18T09:25:00+00:00
             */
            created_at: string | null;
        };
        StoreProjectLessonRequest: {
            /**
             * @description Название нового урока
             * @example Новая лекция
             */
            name: string;
            /**
             * @description Идентификатор версии шаблона. Если поле не передано, API использует `projects.default_pipeline_version_id`.
             * @example 7
             */
            pipeline_version_id?: number | null;
            /**
             * Format: binary
             * @description Аудиофайл размером до 500 MB. Допустимые MIME-типы: audio/mpeg, audio/mp3, audio/wav, audio/x-wav, audio/mp4, audio/x-m4a, audio/aac, audio/ogg, audio/webm, audio/flac.
             */
            file: string;
        };
        UnauthorizedError: {
            /** @example Unauthorized. */
            message: string;
        };
        NotFoundError: {
            /** @example Not Found. */
            message: string;
        };
        ValidationError: {
            /** @example The given data was invalid. */
            message: string;
            errors: {
                [key: string]: string[];
            };
        };
    };
    responses: never;
    parameters: {
        /** @description Числовой идентификатор проекта */
        ProjectId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFolders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список папок и проектов, доступных авторизованному пользователю */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoldersResponse"];
                };
            };
            /** @description Отсутствует или неверен bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Unauthorized."
                     *     }
                     */
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    listProjectLessons: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Числовой идентификатор проекта */
                project: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Проект и его уроки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLessonsResponse"];
                };
            };
            /** @description Отсутствует или неверен bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Проект не существует или недоступен текущему пользователю */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Not Found."
                     *     }
                     */
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    createProjectLessonFromAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Числовой идентификатор проекта */
                project: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["StoreProjectLessonRequest"];
            };
        };
        responses: {
            /** @description Урок создан, нормализация аудио поставлена в очередь */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLessonCreateResponse"];
                };
            };
            /** @description Отсутствует или неверен bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Проект не существует или недоступен текущему пользователю */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Not Found."
                     *     }
                     */
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Ошибка валидации запроса */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
}
